# Docker images, Helm charts, Azure Container Registry and Azure Kubernetes Service.
# This is an Azure DevOps pipeline 100% written in YAML. It is designed to be stored directly in your repository.
# This pipeline uses the strategy/matrix keyword to run multiple parallel pipeline processes, which;
# 1) build docker images
# 2) push docker images to ACR
# 3) package Helm charts (*feature still in preview*)
# 4) push Helm packages to ACR (*feature still in preview*)
# 5) publish image+helm chart to Azure Kubernetes Service (AKS).

trigger:
- master

resources:
- repo: self

#**************************************************
#**** substitute below variables with your own ****
#**************************************************
variables:
  azureSubscription: myServiceConnectionId
  azureResourceGroup: myResourceGroupName
  acrName: myACRName
  kubernetesCluster: myAKSClusterName
  AKS.Deploy: false                     #on/off switch
  registry: $(acrName).azurecr.io       #only change registry if your ACR is non-Azure
  ACR.Deploy: false                     #on/off switch

stages:
- stage: build
  displayName: Build & push Docker images and Helm charts to ACR
  jobs:
  - job: build
    strategy:
      matrix:
        MyApp:
          repository: myapp
          repositoryExact: MyApp
        MyWeb:
          repository: myweb
          repositoryExact: MyWeb
        MyWebAPI:
          repository: mywebapi
          repositoryExact: MyWebAPI
        #add additional builds in here...
    pool:
      vmImage: ubuntu-latest
    steps:
    - template: steps-build-and-push-docker-images.yml
    - template: steps-build-and-push-helm-charts.yml
        
- stage: deploy
  dependsOn: build
  jobs:
  - job: deploy
    displayName: Deploy to AKS via Helm Charts stored in ACR
    condition: and(succeeded(), eq(variables['AKS.Deploy'], 'true'))
    strategy:
      matrix:
        MyApp:
          repository: myapp
          repositoryExact: MyApp
        MyWeb:
          repository: myweb
          repositoryExact: MyWeb
        MyWebAPI:
          repository: mywebapi
          repositoryExact: MyWebAPI
        #add additional deployments in here...
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo $(repository) deployment disabled
    #- template: steps-deploy-helm-charts.yml    