steps:

- task: HelmInstaller@0
  displayName: Install Helm 2.11.0
  inputs:
    helmVersion: 2.11.0

- task: HelmDeploy@0
  displayName: helm init
  inputs:
    azureSubscription: $(azureSubscription)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    command: init
    arguments: --upgrade --canary-image

- task: AzureCLI@1
  displayName: az acr helm repo add -n $(acrName)
  inputs:
    azureSubscription: $(azureSubscription)
    scriptLocation: inlineScript
    inlineScript: az acr helm repo add -n $(acrName) --verbose

- task: HelmDeploy@0
  displayName: helm upgrade $(acrName)/$(repository) --install --force --version $(Build.BuildId) --set image.tag=$(Build.BuildNumber)
  inputs:
    connectionType: Azure Resource Manager
    azureSubscription: $(azureSubscription)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    command: upgrade
    chartName: $(acrName)/$(repository) 
    releaseName: $(repository)
    arguments: --install --force --version $(Build.BuildId) --set image.tag=$(Build.BuildNumber)
