steps:

- task: HelmInstaller@0
  displayName: Install Helm 2.11.0
  inputs:
    helmVersion: 2.11.0

- task: HelmDeploy@0
  displayName: helm init
  condition: and(succeeded(), eq(variables['ACR.Deploy'], 'true'))
  inputs:
    azureSubscription: $(azureSubscription)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    command: init
    arguments: --client-only

- task: HelmDeploy@0
  displayName: helm package
  condition: and(succeeded(), eq(variables['ACR.Deploy'], 'true'))
  inputs:
    azureSubscription: $(azureSubscription)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    command: package
    chartPath: $(repositoryExact)/charts/$(repository)
    chartVersion: $(Build.BuildId)
    destination: $(Build.ArtifactStagingDirectory)

- task: AzureCLI@1
  displayName: Push helm chart
  condition: and(succeeded(), eq(variables['ACR.Deploy'], 'true'))
  inputs:
    azureSubscription: $(azureSubscription)
    scriptLocation: inlineScript
    inlineScript: az acr helm push -n $(acrName) $(Build.ArtifactStagingDirectory)/$(repository)-$(Build.BuildId).tgz